import type { Metadata } from "next";
import { satoshi } from "@/lib/fonts";
import "./globals.css";
import MainNav from "@/components/organisms/nav/components/MainNav";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${satoshi.variable} antialiased font-satoshi`}>
				<MainNav />
				{children}
			</body>
		</html>
	);
}
