import type { Metadata } from "next";
import { satoshi, archivo } from "@/lib/fonts";
import "./globals.css";
import MainNav from "@/components/organisms/nav/components/MainNav";
import WavyToggleButton from "@/components/ui/wavy-button";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				{/* DNS prefetch and preconnect for Google Maps API */}
				<link rel="dns-prefetch" href="//maps.googleapis.com" />
				<link rel="dns-prefetch" href="//maps.gstatic.com" />
				<link rel="preconnect" href="https://maps.googleapis.com" />
				<link rel="preconnect" href="https://maps.gstatic.com" />
			</head>
					<body className={`${satoshi.variable} ${archivo.variable} antialiased font-satoshi`}>
			<MainNav />
			{children}
			<WavyToggleButton audioSrc="/media/AboveSmoke-SaveUs.mp3" />
		</body>
		</html>
	);
}
